[plugin-info]
SHORT_PLUGIN_NAME = 'spectrum_instrumentation'

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_spectrum_instrumentation' #to modify
description = 'An implementation for Spectrum DAQ cards with Lock-In functionalities'

author = 'Malo Hervé'
author-email = 'malo.hervé@epfl.ch'
license = 'DQML'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.1.0']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

